global using VkPhysicalDeviceShaderFloat16Int8FeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceShaderFloat16Int8Features;
global using VkPhysicalDeviceFloat16Int8FeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceShaderFloat16Int8Features;
