global using VkPhysicalDeviceGlobalPriorityQueryFeaturesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceGlobalPriorityQueryFeaturesKHR;
global using VkQueueFamilyGlobalPriorityPropertiesEXT = Exomia.Vulkan.Api.Core.VkQueueFamilyGlobalPriorityPropertiesKHR;
