global using VkPhysicalDeviceMaintenance4FeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceMaintenance4Features;
global using VkPhysicalDeviceMaintenance4PropertiesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceMaintenance4Properties;
global using VkDeviceBufferMemoryRequirementsKHR = Exomia.Vulkan.Api.Core.VkDeviceBufferMemoryRequirements;
global using VkDeviceImageMemoryRequirementsKHR = Exomia.Vulkan.Api.Core.VkDeviceImageMemoryRequirements;
