global using VkPerformanceCounterDescriptionFlagsKHR = Exomia.Vulkan.Api.Core.VkPerformanceCounterDescriptionFlagBitsKHR;
global using VkAcquireProfilingLockFlagsKHR = Exomia.Vulkan.Api.Core.VkAcquireProfilingLockFlagBitsKHR;
