global using VkPhysicalDeviceMaintenance3PropertiesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceMaintenance3Properties;
global using VkDescriptorSetLayoutSupportKHR = Exomia.Vulkan.Api.Core.VkDescriptorSetLayoutSupport;
