global using VkPhysicalDeviceBufferDeviceAddressFeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceBufferDeviceAddressFeatures;
global using VkBufferDeviceAddressInfoKHR = Exomia.Vulkan.Api.Core.VkBufferDeviceAddressInfo;
global using VkBufferOpaqueCaptureAddressCreateInfoKHR = Exomia.Vulkan.Api.Core.VkBufferOpaqueCaptureAddressCreateInfo;
global using VkMemoryOpaqueCaptureAddressAllocateInfoKHR = Exomia.Vulkan.Api.Core.VkMemoryOpaqueCaptureAddressAllocateInfo;
global using VkDeviceMemoryOpaqueCaptureAddressInfoKHR = Exomia.Vulkan.Api.Core.VkDeviceMemoryOpaqueCaptureAddressInfo;
