global using VkPhysicalDeviceMutableDescriptorTypeFeaturesVALVE = Exomia.Vulkan.Api.Core.VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT;
global using VkMutableDescriptorTypeListVALVE = Exomia.Vulkan.Api.Core.VkMutableDescriptorTypeListEXT;
global using VkMutableDescriptorTypeCreateInfoVALVE = Exomia.Vulkan.Api.Core.VkMutableDescriptorTypeCreateInfoEXT;
