global using VkPhysicalDeviceSubgroupSizeControlFeaturesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceSubgroupSizeControlFeatures;
global using VkPhysicalDeviceSubgroupSizeControlPropertiesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceSubgroupSizeControlProperties;
global using VkPipelineShaderStageRequiredSubgroupSizeCreateInfoEXT = Exomia.Vulkan.Api.Core.VkPipelineShaderStageRequiredSubgroupSizeCreateInfo;
