global using VkIndirectCommandsLayoutUsageFlagsEXT = Exomia.Vulkan.Api.Core.VkIndirectCommandsLayoutUsageFlagBitsEXT;
global using VkIndirectCommandsInputModeFlagsEXT = Exomia.Vulkan.Api.Core.VkIndirectCommandsInputModeFlagBitsEXT;
