global using VkVideoEncodeFlagsKHR = Exomia.Vulkan.Api.Provisional.VkVideoEncodeFlagBitsKHR;
global using VkVideoEncodeRateControlFlagsKHR = Exomia.Vulkan.Api.Provisional.VkVideoEncodeRateControlFlagBitsKHR;
global using VkVideoEncodeRateControlModeFlagsKHR = Exomia.Vulkan.Api.Provisional.VkVideoEncodeRateControlModeFlagBitsKHR;
