global using VkPhysicalDevicePointClippingPropertiesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDevicePointClippingProperties;
global using VkPointClippingBehaviorKHR = Exomia.Vulkan.Api.Core.VkPointClippingBehavior;
global using VkRenderPassInputAttachmentAspectCreateInfoKHR = Exomia.Vulkan.Api.Core.VkRenderPassInputAttachmentAspectCreateInfo;
global using VkInputAttachmentAspectReferenceKHR = Exomia.Vulkan.Api.Core.VkInputAttachmentAspectReference;
global using VkImageViewUsageCreateInfoKHR = Exomia.Vulkan.Api.Core.VkImageViewUsageCreateInfo;
global using VkTessellationDomainOriginKHR = Exomia.Vulkan.Api.Core.VkTessellationDomainOrigin;
global using VkPipelineTessellationDomainOriginStateCreateInfoKHR = Exomia.Vulkan.Api.Core.VkPipelineTessellationDomainOriginStateCreateInfo;
