global using VkPhysicalDeviceImagelessFramebufferFeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceImagelessFramebufferFeatures;
global using VkFramebufferAttachmentsCreateInfoKHR = Exomia.Vulkan.Api.Core.VkFramebufferAttachmentsCreateInfo;
global using VkFramebufferAttachmentImageInfoKHR = Exomia.Vulkan.Api.Core.VkFramebufferAttachmentImageInfo;
global using VkRenderPassAttachmentBeginInfoKHR = Exomia.Vulkan.Api.Core.VkRenderPassAttachmentBeginInfo;
