global using VkDescriptorSetLayoutBindingFlagsCreateInfoEXT = Exomia.Vulkan.Api.Core.VkDescriptorSetLayoutBindingFlagsCreateInfo;
global using VkPhysicalDeviceDescriptorIndexingFeaturesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceDescriptorIndexingFeatures;
global using VkPhysicalDeviceDescriptorIndexingPropertiesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceDescriptorIndexingProperties;
global using VkDescriptorSetVariableDescriptorCountAllocateInfoEXT = Exomia.Vulkan.Api.Core.VkDescriptorSetVariableDescriptorCountAllocateInfo;
global using VkDescriptorSetVariableDescriptorCountLayoutSupportEXT = Exomia.Vulkan.Api.Core.VkDescriptorSetVariableDescriptorCountLayoutSupport;
global using VkDescriptorBindingFlagBitsEXT = Exomia.Vulkan.Api.Core.VkDescriptorBindingFlagBits;
global using VkDescriptorBindingFlagsEXT = Exomia.Vulkan.Api.Core.VkDescriptorBindingFlagBits;
