global using VkPhysicalDeviceFloatControlsPropertiesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceFloatControlsProperties;
global using VkShaderFloatControlsIndependenceKHR = Exomia.Vulkan.Api.Core.VkShaderFloatControlsIndependence;
