global using VkPhysicalDeviceInlineUniformBlockFeaturesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceInlineUniformBlockFeatures;
global using VkPhysicalDeviceInlineUniformBlockPropertiesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceInlineUniformBlockProperties;
global using VkWriteDescriptorSetInlineUniformBlockEXT = Exomia.Vulkan.Api.Core.VkWriteDescriptorSetInlineUniformBlock;
global using VkDescriptorPoolInlineUniformBlockCreateInfoEXT = Exomia.Vulkan.Api.Core.VkDescriptorPoolInlineUniformBlockCreateInfo;
