global using VkPhysicalDeviceBufferAddressFeaturesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceBufferDeviceAddressFeaturesEXT;
global using VkBufferDeviceAddressInfoEXT = Exomia.Vulkan.Api.Core.VkBufferDeviceAddressInfo;
