#region License

// Copyright (c) 2018-2022, exomia
// All rights reserved.
// 
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

#endregion

// ReSharper disable UnusedMember.Global
// ReSharper disable InconsistentNaming
// ReSharper disable once CheckNamespace
namespace Exomia.Vulkan.Api.Core;

/// <summary>
///     VkPipelineFragmentShadingRateEnumStateCreateInfoNV - Structure specifying parameters controlling the fragment
///     shading rate using rate enums -
///     <a
///         href="https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineFragmentShadingRateEnumStateCreateInfoNV.html">
///         https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineFragmentShadingRateEnumStateCreateInfoNV.html
///     </a>
/// </summary>
/// <remarks>
///     <list type="table">
///         <item>
///             <term>structextends</term><description>VkGraphicsPipelineCreateInfo</description>
///         </item>
///     </list>
/// </remarks>
[VkStructExtends("VkGraphicsPipelineCreateInfo")]
[StructLayout(LayoutKind.Sequential)]
public unsafe struct VkPipelineFragmentShadingRateEnumStateCreateInfoNV
{
    /// <summary> The stype of this structure. </summary>
    public const VkStructureType STYPE = VK_STRUCTURE_TYPE_PIPELINE_FRAGMENT_SHADING_RATE_ENUM_STATE_CREATE_INFO_NV;

    /// <summary>sType is the type of this structure.</summary>
    public VkStructureType sType;

    /// <summary>pNext is NULL or a pointer to a structure extending this structure.</summary>
    public void* pNext;

    /// <summary>
    ///     shadingRateType specifies a VkFragmentShadingRateTypeNVvalue indicating whether fragment shading rates are
    ///     specified using fragment sizes or VkFragmentShadingRateNV enums.
    /// </summary>
    public VkFragmentShadingRateTypeNV shadingRateType;

    /// <summary>shadingRate specifies a VkFragmentShadingRateNV value indicating the pipeline fragment shading rate.</summary>
    public VkFragmentShadingRateNV shadingRate;

    /// <summary>
    ///     combinerOps specifies VkFragmentShadingRateCombinerOpKHRvalues determining how the pipeline, primitive, and
    ///     attachment shading ratesare combined for fragments generated by drawing commands using the created pipeline.
    /// </summary>
    public VkArray2<VkFragmentShadingRateCombinerOpKHR> combinerOps;
}