global using VkPhysicalDeviceSeparateDepthStencilLayoutsFeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures;
global using VkAttachmentReferenceStencilLayoutKHR = Exomia.Vulkan.Api.Core.VkAttachmentReferenceStencilLayout;
global using VkAttachmentDescriptionStencilLayoutKHR = Exomia.Vulkan.Api.Core.VkAttachmentDescriptionStencilLayout;
