global using VkRenderPassMultiviewCreateInfoKHR = Exomia.Vulkan.Api.Core.VkRenderPassMultiviewCreateInfo;
global using VkPhysicalDeviceMultiviewFeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceMultiviewFeatures;
global using VkPhysicalDeviceMultiviewPropertiesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceMultiviewProperties;
