global using VkExternalSemaphoreHandleTypeFlagsKHR = Exomia.Vulkan.Api.Core.VkExternalSemaphoreHandleTypeFlagBits;
global using VkExternalSemaphoreHandleTypeFlagBitsKHR = Exomia.Vulkan.Api.Core.VkExternalSemaphoreHandleTypeFlagBits;
global using VkExternalSemaphoreFeatureFlagsKHR = Exomia.Vulkan.Api.Core.VkExternalSemaphoreFeatureFlagBits;
global using VkExternalSemaphoreFeatureFlagBitsKHR = Exomia.Vulkan.Api.Core.VkExternalSemaphoreFeatureFlagBits;
global using VkPhysicalDeviceExternalSemaphoreInfoKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceExternalSemaphoreInfo;
global using VkExternalSemaphorePropertiesKHR = Exomia.Vulkan.Api.Core.VkExternalSemaphoreProperties;
