global using VkSamplerReductionModeEXT = Exomia.Vulkan.Api.Core.VkSamplerReductionMode;
global using VkSamplerReductionModeCreateInfoEXT = Exomia.Vulkan.Api.Core.VkSamplerReductionModeCreateInfo;
global using VkPhysicalDeviceSamplerFilterMinmaxPropertiesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceSamplerFilterMinmaxProperties;
