global using VkVideoEncodeH265CapabilityFlagsEXT = Exomia.Vulkan.Api.Core.FutureUse32;
global using VkVideoEncodeH265InputModeFlagsEXT = Exomia.Vulkan.Api.Provisional.VkVideoEncodeH265InputModeFlagBitsEXT;
global using VkVideoEncodeH265OutputModeFlagsEXT = Exomia.Vulkan.Api.Provisional.VkVideoEncodeH265OutputModeFlagBitsEXT;
global using VkVideoEncodeH265CreateFlagsEXT = Exomia.Vulkan.Api.Core.FutureUse32;
global using VkVideoEncodeH265CtbSizeFlagsEXT = Exomia.Vulkan.Api.Provisional.VkVideoEncodeH265CtbSizeFlagBitsEXT;
global using VkVideoEncodeH265RateControlStructureFlagsEXT = Exomia.Vulkan.Api.Provisional.VkVideoEncodeH265RateControlStructureFlagBitsEXT;
