global using VkPhysicalDeviceVariablePointerFeatures = Exomia.Vulkan.Api.Core.VkPhysicalDeviceVariablePointersFeatures;
global using VkPhysicalDeviceShaderDrawParameterFeatures = Exomia.Vulkan.Api.Core.VkPhysicalDeviceShaderDrawParametersFeatures;
