global using VkPhysicalDeviceShaderIntegerDotProductFeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceShaderIntegerDotProductFeatures;
global using VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceShaderIntegerDotProductProperties;
