global using VkPhysicalDeviceVariablePointerFeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceVariablePointersFeatures;
global using VkPhysicalDeviceVariablePointersFeaturesKHR = Exomia.Vulkan.Api.Core.VkPhysicalDeviceVariablePointersFeatures;
