name: '[CI] build & test'
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - development
env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_NOLOGO: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  build-core:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        configurations: [Debug, Release]
    name: '[Core] build ${{ matrix.configurations }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: 5.0.101
    - name: '[Core] build ${{ matrix.configurations }}'
      run: |
        dotnet build src/Exomia.Vulkan.Api.Core --configuration ${{ matrix.configurations }} --force --nologo -p:Platform=AnyCPU
        dotnet build src/Exomia.Vulkan.Api.Core --configuration ${{ matrix.configurations }} --force --nologo -p:Platform=x86
        dotnet build src/Exomia.Vulkan.Api.Core --configuration ${{ matrix.configurations }} --force --nologo -p:Platform=x64
  test-core:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        configurations: [Debug, Release]
    name: '[Core] test ${{ matrix.configurations }} on ${{ matrix.os }}'
    needs: [build-core]
    runs-on: ${{ matrix.os }}
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: 5.0.101
    - name: '[Core] test ${{ matrix.configurations }}'
      run: |
        dotnet test tests/L0/Exomia.Vulkan.Api.Core.Tests --configuration ${{ matrix.configurations }} --nologo -p:Platform=AnyCPU
        dotnet test tests/L0/Exomia.Vulkan.Api.Core.Tests --configuration ${{ matrix.configurations }} --nologo -p:Platform=x86
        dotnet test tests/L0/Exomia.Vulkan.Api.Core.Tests --configuration ${{ matrix.configurations }} --nologo -p:Platform=x64
  build-projects:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        configurations: [Debug, Release]
        projects: [Windows]
    name: '[${{ matrix.projects }}] build ${{ matrix.configurations }} on ${{ matrix.os }}'
    needs: [test-core]
    runs-on: ${{ matrix.os }}
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: 5.0.101
    - name: '[${{ matrix.projects }}] build ${{ matrix.configurations }}'
      run: |
        dotnet build src/Exomia.Vulkan.Api.${{ matrix.projects }} --configuration ${{ matrix.configurations }} --force --nologo -p:Platform=AnyCPU
        dotnet build src/Exomia.Vulkan.Api.${{ matrix.projects }} --configuration ${{ matrix.configurations }} --force --nologo -p:Platform=x86
        dotnet build src/Exomia.Vulkan.Api.${{ matrix.projects }} --configuration ${{ matrix.configurations }} --force --nologo -p:Platform=x64
  test-projects:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        configurations: [Debug, Release]
        projects: [Windows]   
    name: '[${{ matrix.projects }}] test ${{ matrix.configurations }} on ${{ matrix.os }}'
    needs: [build-projects]
    runs-on: ${{ matrix.os }}
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: 5.0.101
    - name: '[${{ matrix.projects }}] test ${{ matrix.configurations }}'
      run: |
        dotnet test tests/L0/Exomia.Vulkan.Api.${{ matrix.projects }}.Tests --configuration ${{ matrix.configurations }} --nologo -p:Platform=AnyCPU
        dotnet test tests/L0/Exomia.Vulkan.Api.${{ matrix.projects }}.Tests --configuration ${{ matrix.configurations }} --nologo -p:Platform=x86
        dotnet test tests/L0/Exomia.Vulkan.Api.${{ matrix.projects }}.Tests --configuration ${{ matrix.configurations }} --nologo -p:Platform=x64
