name: '[CI] build & test'
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - development
env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_NOLOGO: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        configurations: [Debug, Release]
        plattforms: [AnyCPU, x64]
        projects: [Core, Windows, Beta]
    name: '[${{ matrix.projects }}] build ${{ matrix.configurations }} on ${{ matrix.os }}[${{ matrix.plattforms }}]'
    runs-on: ${{ matrix.os }}
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: '5.0.x'
    - name: '[${{ matrix.projects }}] build ${{ matrix.configurations }}'
      run: |
        dotnet build src/Exomia.Vulkan.Api.${{ matrix.projects }} --configuration ${{ matrix.configurations }} --force --nologo -p:Platform=${{ matrix.plattforms }}
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        configurations: [Debug, Release]
        plattforms: [AnyCPU, x64]
        projects: [Core, Windows, Beta]   
    name: '[${{ matrix.projects }}] test ${{ matrix.configurations }} on ${{ matrix.os }}[${{ matrix.plattforms }}]'
    needs: [build]
    runs-on: ${{ matrix.os }}
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: '5.0.x'
    - name: '[${{ matrix.projects }}] test ${{ matrix.configurations }}'
      run: |
        dotnet test tests/L0/Exomia.Vulkan.Api.${{ matrix.projects }}.Tests --configuration ${{ matrix.configurations }} --nologo -p:Platform=${{ matrix.plattforms }}
