global using VkPhysicalDeviceLineRasterizationFeaturesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceLineRasterizationFeaturesKHR;
global using VkPhysicalDeviceLineRasterizationPropertiesEXT = Exomia.Vulkan.Api.Core.VkPhysicalDeviceLineRasterizationPropertiesKHR;
global using VkPipelineRasterizationLineStateCreateInfoEXT = Exomia.Vulkan.Api.Core.VkPipelineRasterizationLineStateCreateInfoKHR;
global using VkLineRasterizationModeEXT = Exomia.Vulkan.Api.Core.VkLineRasterizationModeKHR;
